name: continuous deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v3

      - name: Find new product version
        uses: arwynfr/actions-conventional-versioning/get-newVersion@v3
        id: next-version
        with:
          allow-additional-modifiers: true
          feat-upgrades-minor: false
          strict-types: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: >
          dotnet publish
            src/Gsri.Api.Personnels
            --configuration Release
            /target:PublishContainer
            /property:Version=${{ steps.next-version.outputs.next-version }}
            /property:ContainerRegistry=
            /property:ContainerImageName=ghcr.io/team-gsri/apps-api-personnels

      - name: Publish Docker image
        run: docker push ghcr.io/team-gsri/apps-api-personnels:${{ steps.next-version.outputs.next-version }}

      - name: Publish GitHub release
        uses: arwynfr/actions-conventional-versioning@v3
        with:
          allow-additional-modifiers: true
          feat-upgrades-minor: false
          strict-types: true
