name: continuous integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd "pg_isready -q -h postgres"
            --health-interval 1s
            --health-timeout 5s
            --health-retries 5
    env:
      ConnectionStrings__PersonnelsDbContext: Host=postgres;Port=5432;Database=postgres;User ID=postgres;Password=password;Timeout=120
    steps:

      - name: Checkout source files
        uses: actions/checkout@v3

      - name: Apply database migration
        run : |
          sleep 1m
          dotnet tool install --global dotnet-ef
          dotnet ef database update --project src/Gsri.Api.Personnels

      - name: Running unit tests
        run: dotnet test src
