name: continuous integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v3

      - name: Running unit tests
        run: dotnet test src
